app = 'insightberry-backend'
primary_region = 'waw'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[services]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "16gb"
  cpu_kind = "performance"
  cpus = 4